# Generated by Django 2.2.5 on 2019-09-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='age',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
